# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

users = User.create!([
  { username: 'peter', password: 'eeeeee', display_name: 'Peter' },
  { username: 'elliott', password: 'ffffff', display_name: 'Wind Fish' },
  { username: 'sloslylove', password: 'gggggg' },
  { username: 'guest', password: 'password', display_name: 'Guest' },
])

peter, elliott, sloslylove, guest, _ = users

tracks = Track.create!([
  {
    title: 'Dragonette - Hello (Wind Fish Remix)',
    owner_id: elliott.id,
    audio_file_name: 'sky_palaces.mp3', #might want to rename this
    audio_content_type: "audio/mpeg",
    audio_file_size: 4707575,
    cover_art_file_name: "hello.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 80784,
  },
  {
    title: 'lontalius - i guess itsss (Wind Fish Edit)',
    owner_id: elliott.id,
    audio_file_name: 'i_guess_itsss.mp3',
    audio_content_type: "audio/mpeg",
    audio_file_size: 2784861,
    cover_art_file_name: "i_guess_itsss.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 37939,
  },
  {
    title: 'Airloop',
    owner_id: elliott.id,
    audio_file_name: 'LANDR-airloop.mp3',
    audio_content_type: "audio/mpeg",
    audio_file_size: 5309543,
    cover_art_file_name: "airloop.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 285799,
  },
  {
    title: 'Adelyn Rose - It Means Shadow (Wind Fish Remix)',
    owner_id: elliott.id,
    audio_file_name: "it_means_shadow.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 4610337,
    cover_art_file_name: "it_means_shadow.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 56229,
  },
  {
    title: 'Concourse Bay Ft. Phoenix',
    owner: elliott,
    audio_file_name: "concourse_bay.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 2226292,
    cover_art_file_name: "concourse_bay.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 129946,
  },
  {
    title: 'Empire Builder',
    owner: elliott,
    audio_file_name: "empire_builder.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 3174213,
    cover_art_file_name: "concourse_bay.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 129946,
  },
  {
    title: 'Lonely Bones',
    owner: elliott,
    audio_file_name: "lonely_bones.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 2784673,
    cover_art_file_name: "concourse_bay.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 129946,
  },
  {
    title: 'Spacetime',
    owner: elliott,
    audio_file_name: "spacetime.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 4319316,
    cover_art_file_name: "poozer.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 75597,
  },
  {
    title: 'Variation',
    owner: elliott,
    audio_file_name: "variation.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 3700402,
    cover_art_file_name: "poozer.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 75597,
  },
  {
    title: 'Vibrate',
    owner: elliott,
    audio_file_name: "vibrate.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 4874728,
    cover_art_file_name: "poozer.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 75597,
  },
  {
    title: 'Sounds',
    owner: elliott,
    audio_file_name: "sounds.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 3566060,
    cover_art_file_name: "poozer.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 75597,
  },
  {
    title: 'River',
    owner: elliott,
    audio_file_name: "river.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 9659840,
    cover_art_file_name: "poozer.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 75597,
  },
  {
    title: 'Feels',
    owner: sloslylove,
    audio_file_name: "feels.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 3224972,
    cover_art_file_name: "the_haunted.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 89986,
  },
  {
    title: "Can't Let Go",
    owner: sloslylove,
    audio_file_name: "cant_let_go.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 2895202,
    cover_art_file_name: "the_haunted.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 89986,
  },
  {
    title: 'You And I',
    owner: sloslylove,
    audio_file_name: "you_and_i.mp3",
    audio_content_type: "audio/mpeg",
    audio_file_size: 3633318,
    cover_art_file_name: "the_haunted.jpg",
    cover_art_content_type: "image/jpeg",
    cover_art_file_size: 89986,
  },
  ])

posts = Post.create!([
  { owner: peter, track: tracks[8] },
  { owner: peter, track: tracks[5] },
  { owner: peter, track: tracks[2] },
  { owner: sloslylove, track: tracks[0] },
  { owner: sloslylove, track: tracks[1] },
  { owner: sloslylove, track: tracks[6] },
  { owner: peter, track: tracks[10] },
  { owner: peter, track: tracks[0] },
  { owner: peter, track: tracks[3] },
])

likes = Like.create!([
  { user: peter, track: tracks[0] },
  { user: peter, track: tracks[1] },
  { user: peter, track: tracks[2] },
  { user: guest, track: tracks[0] },
  { user: guest, track: tracks[1] },
  { user: sloslylove, track: tracks[1] },
  { user: sloslylove, track: tracks[3] },
])
